import numpy as np
import pandas as pd
import csv
import matplotlib.pyplot as plt
annee= pd.read_excel("./Results_To_Plot/overheating_annee_hors_chauffe_sans.xlsx", names=["DH","H"])
annee_occ= pd.read_excel("./Results_To_Plot/overheating_annee_hors_chauffe_occ.xlsx", names=["DH","H"])
ete= pd.read_excel("./Results_To_Plot/overheating_ete_sans.xlsx", names=["DH","H"])
ete_occ= pd.read_excel("./Results_To_Plot/overheating_ete_occ.xlsx", names=["DH","H"])
def plot_DH(df):
    fig,axes=plt.subplots(nrows=1,ncols=2,sharex=True,sharey=True,figsize=(5,3.8))
    labels=["SF_sans","SF_avec","NoMASS"]
    barWidth = 0.25
    br1 = np.arange(len(labels))
    #axes[0].bar(br1-barWidth/2,[24067.5,5178.9,annee["DH"].mean()],yerr=[0,0,annee["DH"].std()],width = barWidth,color = 'royalblue',label="Total")
    #axes[0].bar(br1+barWidth/2,[8903.3,2280.8,annee_occ["DH"].mean()],yerr=[0,0,annee_occ["DH"].std()],width = barWidth,color = 'green',label="Pendant l'occupation")
    axes[0].bar(br1-barWidth/2,[22998.3,4598.4,annee["DH"].mean()],yerr=[0,0,annee["DH"].std()],width = barWidth,color = 'royalblue',label="Total")
    axes[0].bar(br1+barWidth/2,[8413.7,2001.3,annee_occ["DH"].mean()],yerr=[0,0,annee_occ["DH"].std()],width = barWidth,color = 'green',label="Pendant l'occupation")
    axes[0].set_ylabel('DH (°C.h)')
    axes[0].axhline(y = 350, color = 'r', linestyle = '-')
    #axes[0,0].set_xticks(br1,labels)
    #box=axes[0,0].boxplot([df["DH"]],labels=["NoMASS"])
    axes[1].bar(br1-barWidth/2,[16675.7,2526.3,ete["DH"].mean()],yerr=[0,0,ete["DH"].std()],width = barWidth,color = 'royalblue',label="Total")
    axes[1].bar(br1+barWidth/2,[5873.5,1070.2,ete_occ["DH"].mean()],yerr=[0,0,ete_occ["DH"].std()],width = barWidth,color = 'green',label="Pendant l'occupation")
    axes[1].set_title('Estival')
    axes[1].axhline(y = 350, color = 'r', linestyle = '-')
    plt.xticks(br1,labels)
    axes[0].set_title('Annuel (hors_chauffe)')
    axes[0].legend(fontsize=7)
    axes[1].legend(fontsize=7)
    axes[0].grid(axis = 'y')
    axes[1].grid(axis = 'y')
    axes[0].set_ylim(0,25000)
    plt.savefig("DH.png")
    plt.show()
def plot_Hours(df):
    fig,axes=plt.subplots(nrows=1,ncols=2,sharex=True,sharey=True,figsize=(5,3.8))
    labels=["SF_sans","SF_avec","NoMASS"]
    barWidth = 0.25
    br1 = np.arange(len(labels))
    #axes[0].bar(br1-barWidth/2,[4843.6,3147.2,annee["H"].mean()],yerr=[0,0,annee["H"].std()],width = barWidth,color = 'royalblue',label="Total")
    #axes[0].bar(br1+barWidth/2,[1660,1079.8,annee_occ["H"].mean()],yerr=[0,0,annee_occ["H"].std()],width = barWidth,color = 'green',label="Pendant l'occupation")
    axes[0].bar(br1-barWidth/2,[4211.4,2649.89,annee["H"].mean()],yerr=[0,0,annee["H"].std()],width = barWidth,color = 'royalblue',label="Total")
    axes[0].bar(br1+barWidth/2,[1400.6,861.6,annee_occ["H"].mean()],yerr=[0,0,annee_occ["H"].std()],width = barWidth,color = 'green',label="Pendant l'occupation")
    axes[0].set_ylabel("Nombre d'heures d'inconfort")
    axes[1].bar(br1-barWidth/2,[2256,1317.3,ete["H"].mean()],yerr=[0,0,ete["H"].std()],width = barWidth,color = 'royalblue',label="Total")
    axes[1].bar(br1+barWidth/2,[719.4,385.5,ete_occ["H"].mean()],yerr=[0,0,ete_occ["H"].std()],width = barWidth,color = 'green',label="Pendant l'occupation")
    plt.xticks(br1,labels)
    axes[0].set_title("Annuel (hors_chauffe)")
    axes[1].set_title("Estival")
    axes[0].legend(fontsize=7)
    axes[1].legend(fontsize=7)
    #axes[0,0].set_xticks(br1,labels)
    axes[0].grid(axis = 'y')
    axes[1].grid(axis = 'y')
    axes[0].set_ylim(0,5000)
    plt.savefig("Hours_discomfort.png")
    plt.show()
plot_DH(annee)
plot_Hours(annee)